export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_RESET_ITEM = "CART_RESET_ITEM";
export const CART_REMOVE_BY_ID = "CART_REMOVE_BY_ID";
